name: Run trace-based tests

on:
  # allows the manual trigger
  workflow_dispatch:

jobs:
  pokeshop-trace-based-tests:
    name: Run trace based tests for Pokeshop
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Tracetest CLI
        uses: kubeshop/tracetest-github-action@v1
        with:
          token: ${{secrets.TRACETEST_CLI_TOKEN}}

      - name: Inject secrets as a variable set on Tracetest
        run: |
          cat << EOF > vars.yaml
          type: VariableSet
          spec:
            id: tracetesting-vars
            name: AuthKeys for test
            description: Variables used in basic auth for my API
            values:
            - key: USER
              value: admin
            - key: PASSWORD
              value: ${{secrets.API_SECRET_PASSWORD}}
              type: secret
          EOF

          tracetest apply variableset --file ./vars.yaml

      - name: Run trace-based tests
        run: |
          tracetest run test --vars tracetesting-vars --file ./test-with-success.yaml